config/routes.rb
Rails.application.routes.draw do
  get 'twitter_search/new'
  get 'twitter_search/history'
  post 'twitter_search/search'

  root to: 'home#index'

  devise_for :users

end

app/models/generic_search_result.rb
class GenericSearchResult

	attr_accessor :author, :text

	def initialize(attributes = {})
		self.author = attributes[:author] || ''
		self.text = attributes[:text] || ''
	end

	def self.parse_twitter(search_results)
		search_results.map do |r|
			self.new author: r.user.screen_name, text: r.text
		end
	end

	def self.load_from_json_text(json_blob)
		self.load_from_hash JSON.load(json_blob)
	end


	private

	def self.load_from_hash(search_results)
		search_results.map do |r|
			self.new author: r['author'.freeze], text: r['text'.freeze]
		end
	end
end

app/models/search_history_entry.rb
# == Schema Information
#
# Table name: search_history_entries
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  results_blob :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_search_history_entries_on_user_id  (user_id)
#

class SearchHistoryEntry < ActiveRecord::Base
  belongs_to :user

	def self.add_user_search_results(user, results_json)
		self.create! user: user, results_blob: results_json

	rescue => e
		Rails.logger.error "SearchHistoryEntry#add_user_search_results(#{user}, #{results_json}) failed. #{e.message}"
		false
	end
end

app/models/twitter_client.rb
class TwitterClient
	MAX_RECENT_TWEETS = 10

	def self.recent_tweets(term)
		$twitter.search(term, result_type: "recent").take(MAX_RECENT_TWEETS)
	rescue => e
		Rails.logger.error "Failed fetching recent tweets: #{e.message}"
		nil
	end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :search_history_entries

	def recent_searches
		search_history_entries.order(id: :desc).map do |entry|
			{
				date: entry.created_at.to_s(:short),
				results: GenericSearchResult.load_from_json_text(entry.results_blob)
			}
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/twitter_search_controller.rb
class TwitterSearchController < ApplicationController
	before_action :authenticate_user!

  def new
  end

  def search

    unless safe_search_params['term']['tomato']
      redirect_to twitter_search_new_path, notice: 'Search term should include \'tomato\''
      return
    end

    @recent_tweets = TwitterClient.recent_tweets safe_search_params['term']

    if @recent_tweets
			SearchHistoryEntry.add_user_search_results current_user, GenericSearchResult.parse_twitter(@recent_tweets).to_json
    end
  end

  def history

		@search_history = current_user.recent_searches

  end

  private

  def safe_search_params
    params.require(:search).permit(:term)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/twitter_search_helper.rb
module TwitterSearchHelper
end

app/views/home/index.html.erb
<h1>Welcome to The Tweetomator</h1>
<p class="lead">
	Tweetomator is a Rails app that allows users to search for tomato related tweets (tweets that have the word tomato in them).
	Each user also has access to his previous search history including the date of the search and the top 10 results that the user got.

	<p>
		<%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary' %>
	</p>
</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
	<li>
		<%= link_to 'Twitter search', twitter_search_new_path %>
	</li>
	<li>
		<%= link_to 'Search history', twitter_search_history_path %>
	</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tweetomator" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tweetomator" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/twitter_search/history.html.erb
<h1>Search history</h1>
<% @search_history.each do |entry| %>
	<div class="container">
		<h3><%= entry[:date] %></h3>
		<p>
			<dl>
				<% entry[:results].each do |t| %>
					<dt><em><%= t.author %></em> says:</dt>
					<dd><%= t.text %></dd>
				<% end %>
			</dl>
		</p>
	</div>
<% end %>

app/views/twitter_search/new.html.erb
<h1>Tomatos search form</h1>
<%= form_for 'search', url: twitter_search_search_path, method: :post, html: { class: 'form-inline'} do |f| %>
	<div class="form-group">
		<%= f.text_field :term, class: 'form-control', placeholder: 'search for tomatos...' %>
	</div>
	<%= f.submit 'Search', class: 'btn btn-primary' %>
<% end %>

app/views/twitter_search/search.html.erb
<h1>Recent tweets for <em><%= params[:search][:term] %></em></h1>

<% if @recent_tweets.present? %>
	<p>
		<%= link_to 'Back to search form', :back %>
	</p>
	<dl>
		<% @recent_tweets.each do |t| %>
			<dt><em><%= t.user.screen_name %></em> says:</dt>
			<dd><%= t.text %></dd>
		<% end %>
	</dl>
<% else %>
	<p>
		Nothing found. <%= link_to 'Back to search form', :back %>
	</p>
<% end %>